

version: "3.9"
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ejemplo
    volumes:
      - datos_mysql:/var/lib/mysql
    networks:
      - backend
  go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=330
    networks:
      - backend
      - frontend
    depends_on:
      - db

volumes:
  datos_mysql:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge