

version: "3.9"
services:
  web:
    image: nginx:stable-otel
      networks:
      - frontend
      - backend


volumes:
  datos_mysql:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge